version: '3.8'

services:

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "9090:8081"
    depends_on:
      - redis
    environment:
      - SPRING_DATA_REDIS_HOST=redis

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"